// react-board/src/pages/BoardDetail.jsx
import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import axios from 'axios'

function BoardDetail() {

  const { id } = useParams()
  const navigate = useNavigate()

  const [post, setPost] = useState(null)


  useEffect(() => {

    async function fetchPost() {

      const response = await axios.get(
        `http://localhost:9090/api/posts/${id}`
      )

      setPost(response.data)

    }

    fetchPost()

  }, [id])


  if (!post) {
    return <div>게시글을 불러오는 중입니다...</div>
  }


  return (
    <div>

      <h1>게시글 상세</h1>

      <p>번호 : {post.id}</p>

      <h2>{post.title}</h2>

      <div>
        {post.content}
      </div>

      <br />

      <button onClick={() => navigate('/board')}>
        목록
      </button>

    </div>
  )
}

export default BoardDetail

// vue-board/src/views/BoardDetail.vue
<template>

<h1>게시글 상세</h1>

<div v-if="post">

    <p>번호 : {{ post.id }}</p>
    <h2>제목 : {{ post.title }}</h2> 
    <h2>내용 : {{ post.content }}</h2>

</div>


<button @click="goList">
목록
</button>


</template>


<script setup>

import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import axios from 'axios'


const route = useRoute()
const router = useRouter()


const post = ref(null)

console.log(route.params);
async function fetchPost(){

    const response = await axios.get(
        `http://localhost:9090/api/posts/${route.params.id}`
    )


    post.value = response.data

}


function goList(){

    router.push('/board')

}


onMounted(() => {

    fetchPost()

})


</script>
